# Spring Boot
spring.application.name=FinPocket

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE:finpocket_db}

# JWT Configuration
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION:86400000}

# Server Configuration
server.port=${SERVER_PORT:8080}

# Logging
logging.level.com.finpocket=DEBUG
logging.level.org.springframework.security=DEBUG

# FinPocket Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${FINPOCKET_MAIL_USERNAME}
spring.mail.password=${FINPOCKET_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true