# Spring Boot
spring.application.name=FinPocket

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://palurikusalaprabhaprasadini16_db_user:FinPocket@finpocket.hcf6xdn.mongodb.net/?appName=FinPocket}
spring.data.mongodb.database=${MONGODB_DATABASE:finpocket_db}

# JWT Configuration
app.jwt.secret=${JWT_SECRET:i7Nu0/yZMNGhaID1UHO+GN4teavm5MzPGy+5Pf62kaI=}
app.jwt.expiration=${JWT_EXPIRATION:86400000}

# Server Configuration
server.port=${SERVER_PORT:10000}

# Logging
logging.level.com.finpocket=INFO
logging.level.org.springframework.security=INFO

# FinPocket Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${FINPOCKET_MAIL_USERNAME:palurikusalaprabhaprasadini16@gmail.com}
spring.mail.password=${FINPOCKET_MAIL_PASSWORD:zdcf mkke zdqw obwr}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Frontend URL for email links (verification, password reset)
app.frontend.url=${FRONTEND_URL:http://localhost:5500}